# Run locally with:
#   pre-commit install
#   pre-commit run --all-files
# These hooks complement scripts/check_style.sh:
# - black + isort + ruff will auto-fix most issues
# - mypy / bandit are non-fixing checks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        files: ^src/mlstream/
      - id: end-of-file-fixer
        files: ^src/mlstream/
      - id: mixed-line-ending
        files: ^src/mlstream/
      - id: trailing-whitespace
        files: ^src/mlstream/

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
        files: ^src/mlstream/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        language_version: python3.12
        files: ^src/mlstream/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
        language_version: python3.12
        files: ^src/mlstream/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
        args: ["--show-error-codes", "--pretty"]
        language_version: python3.12
        files: ^src/mlstream/  # only type-check files under src/mlstream

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        # Bandit scans recursively starting at src/mlstream
        args: ["-r", "src/mlstream"]
        language_version: python3.12
        files: ^src/mlstream/
