name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  pre-commit:
    name: pre-commit (fast local checks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  style-and-types:
    name: scripts/check_style.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install tools (black, isort, ruff, mypy, bandit)
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff mypy bandit

      - name: Make scripts executable (just in case)
        run: |
          chmod +x scripts/check_style.sh || true
          chmod +x scripts/format.sh || true

      - name: Run checks
        env:
          TARGETS: "src/mlstream"
        run: ./scripts/check_style.sh
